# Basic dependabot.yml

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target_branch: "main"
    schedule:
      interval: "weekly"
      

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    target_branch: "main"
    schedule:
      interval: "live"
      